### ISSUE TITLE
The webpage is not available.

### ISSUE THREAD

**Issue by datomnurdin** [kayrules/solatjakim-api-site#1]
Something wrong happen on your site, http://api.kayrules.com/solatjakim.

**Comment by kayrules** [comment]
Thank you for reporting this.
I've fixed the dns record. Somehow it was accidentally deleted.
need some time to propagate the dns record.

pls try again later.

Regards.

**Comment by datomnurdin** [comment]
Noted.

**Comment by datomnurdin** [comment]
Fixed. Thanks.
