### ISSUE TITLE
Question about the API documentation page

### ISSUE THREAD

**Issue by zulhfreelancer** [kayrules/solatjakim-api-site#2]
Hi bro,

What the theme name/software you use to create this beautiful API documentation page?
http://api.kayrules.com/solatjakim/reference/times/today

It's really nice!

Mind to share?

**Comment by kayrules** [comment]
the theme is actually a paid theme (https://themeforest.net/item/-/6228450). the backend is on php-laravel framework.

**Comment by zulhfreelancer** [comment]
Thanks!
